name: test-pipine
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_previous_job_start_time:
    runs-on: ubuntu-latest
    steps:
      - name: check check_previous_job_start_time
        id: check_previous_job_start_time
        uses: actions/github-script@v7
        env:
          workflow-initiator: ${{ github.event.workflow_run.actor }}
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { data: runs } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "test-pipine.yaml",
              status: 'completed'
            });

            core.info(`Found ${runs.workflow_runs[0].created_at} runs for this workflow.`);
            core.info(`Found ${runs.workflow_runs[0].created_at} runs for this workflow.`);

            const previousRun = runs.workflow_runs.find(run => run.id !== context.runId);




            if (previousRun) {
              core.setOutput('previous_run_start_time', previousRun);

            core.info(`Previous run created at: ${previousRun ? previousRun.created_at : 'No previous run found'}`);

            const previous_run_created_at = previousRun ? previousRun.created_at : 'No previous run found';

            if (previousRun) {
              const previousRunTime = new Date(previousRun.created_at).getTime();
              const currentRunTime = new Date(context.runStartedAt).getTime();
              const timeDifference = (currentRunTime - previousRunTime) / (1000 * 60); // Convert to minutes

              if (timeDifference <= 5) {
                core.info('Previous run happened within 5 minutes.');
                core.setOutput('previous_run_within_5_minutes', true);
              } else {
                core.info('Previous run did not happen within 5 minutes.');
                core.setOutput('previous_run_within_5_minutes', false);
              }
            }    

            } else {
              core.setOutput('previous_run_start_time', 'No previous run found');
            }

            core.info('current_run_start_time', context.runStartedAt);
