name: test-pipine
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_previous_job_start_time:
    runs-on: ubuntu-latest
    steps:
      - name: check check_previous_job_start_time
        id: check_previous_job_start_time
        uses: actions/github-script@v7
        env:
          workflow-initiator: ${{ github.event.workflow_run.actor }}
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: context.workflow,
              branch: 'main',
              status: 'in_progress',
              per_page: 2
            });

            const runsComplete = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: context.workflow,
              branch: 'main',
              status: 'completed',
              per_page: 2
            });

            core.info('All runs:', runs.data.workflow_runs.find(run => run.id !== context.runId));
            core.info('All runs:', runsComplete.data.workflow_runs.find(run => run.id !== context.runId));

            const previousRun = runs.data.workflow_runs.find(run => run.id !== context.runId);
            core.info('Previous run found:', previousRun);

            if (previousRun) {
              core.setOutput('previous_run_start_time', previousRun);
            } else {
              core.setOutput('previous_run_start_time', 'No previous run found');
            }

            core.info('current_run_start_time', context.payload.workflow_run);
