name: test-pipine
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_previous_job_start_time:
    runs-on: ubuntu-latest
    steps:
      - name: check check_previous_job_start_time
        id: check_previous_job_start_time
        uses: actions/github-script@v7
        env:
          workflow-initiator: ${{ github.event.workflow_run.actor }}
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { data: runs } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "test-pipine.yaml",
              status: 'completed',
            });

            const previousRun = runs.workflow_runs.find(run => run.id !== context.runId);
            core.info(`Previous run created at: ${previousRun ? previousRun.created_at : 'No previous run found'}`);
            core.info(`Previous run ID: ${previousRun ? previousRun.id : 'No previous run found'}`);

            if (previousRun) {
              const previousRunTime = new Date(previousRun.created_at).getTime();
              core.info(`Previous run time in ms: ${previousRunTime}`);

              const fiveMinutesInMillis = 5 * 60 * 1000;
              const currentTime = Date.now();

              if (currentTime - previousRunTime > fiveMinutesInMillis) {
                core.info(`Previous run happened more than 5 minutes ago`);
              } else {
                core.info(`Previous run happened within 5 minutes ago, restarting run.`);

              }
            }

            core.info(`current_run context run id ${context.runId} | time now ${Date.now()} `);
            core.info(`current_run context run id ${context.runId} | time now ${Date.now()} `);
