name: test-pipine
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_previous_job_start_time:
    runs-on: ubuntu-latest
    steps:
      - name: check check_previous_job_start_time
        id: check_previous_job_start_time
        uses: actions/github-script@v7
        env:
          workflow-initiator: ${{ github.event.workflow_run.actor }}
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { data: runs } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "test-pipine.yaml",
              status: 'completed'
            });

            core.info(`Found ${runs.workflow_runs[0].created_at} runs for this workflow.`);

            const previousRun = runs.workflow_runs.find(run => run.id !== context.runId);

            if (previousRun) {
              core.setOutput('previous_run_start_time', previousRun);
            } else {
              core.setOutput('previous_run_start_time', 'No previous run found');
            }

            core.info('current_run_start_time', context.payload.workflow_run);
